=== DUMIE505/qsp-protocol-node/plugins/analyzers/schema/analyzer_integration.json
{
    "$schema": "http://json-schema.org/schema#",
    "id": "http://quantstamp.com/schemas/analyzer.json",
    "version": "0.0.1",
    "type": "object",
    "title": "Audit report",
    "description": "API schema defining the expected output format of an audit report",
    "additionalProperties": false,
    "required": [
        "status"
    ],
    "properties": {
        "timestamp": {
            "type": "integer",
            "description": "The UTC time in which in this report was produced"
        },
        "audit_state": {
            "type": "integer",
            "description": "The AuditState of the report, as defined in QuantstampAuditData",
            "minimum": 0,
            "maximum": 6
        },
        "version": {
            "type": "string",
            "description": "The version of the audit node"
        },
        "contract_uri": {
            "type": "string",
            "description": "The UTC time in which in this report was produced"
        },
        "contract_hash": {
            "type": "string",
            "pattern": "^[A-Fa-f0-9]{64}$",
            "description": "Hash digest (sha256) of the target contract" 
        },
        "compilation_errors": {
            "type": "array",
            "items": {
                "type": "string"
            },
            "description": "The list of compilation errors preventing the code from compiling"
        },
        "compilation_warnings": {
            "type": "array",
            "items": {
                "type": "string"
            },
            "description": "The list of compilation warnings that do not prevent the code from compiling"
        },
        "requestor": {
            "type": "string",
            "pattern": "^(0x)?[A-Fa-f0-9]{40}$",
            "description": "The account address of the party requesting the audit"
        },
        "auditor": {
            "type": "string",
            "pattern": "^(0x)?[A-Fa-f0-9]{40}$",
            "description": "The account address of the party producing the audit"
        },
        "request_id": {
            "type": "integer"
        },
        "status": {
            "type": "string",
            "enum": [
                "success",
                "error"
            ],
            "description": "Status result of whether the audit was successfully produced or not"
        },
        "analyzers_reports": {
            "type": "array",
            "items": {
                "type": "object",
                "required": [
                    "analyzer",
                    "status"
                ],
                "properties": {
                    "start_time": {
                        "type": "integer",
                        "description": "The starting time (epoch) that the analyzer started execution",
                        "minimum": 1                    
                    },
                    "end_time": {
                        "type": "integer",
                        "description": "The end time (epoch) that the analyzer ended execution",
                        "minimum": 1                    
                    },
                    "analyzer": {
                        "type":  "object",
                        "description": "Meta data concerning the underlying analyzer",
                        "required": ["name"],
                        "properties": {
                            "name": {
                                "description": "Analyzer's name",
                                "type": "string",
                                "maxLength": 50
                            },
                            "version": {
                                "description": "Analyzer's version",
                                "type": "string",
                                "maxLength": 64
                            },
                            "vulnerabilities_checked": {
                                "type": "object",
                                "patternProperties": {
                                    "^.*$": { 
                                        "type": "object",
                                        "properties": {
                                            "type": {
                                                "type": "string"
                                            }
                                        },
                                        "required": ["type"]
                                    }
                                }                     
                            },
                            "command": {
                                "type": "string",
                                "description": "Command used when executing the analyzer for the given report"
                            }
                        }
                    },
                    "status": {
                        "enum": ["success", "error"],
                        "description": "Status result of whether the analyzer succeeded or not"
                    },
                    "errors": {
                        "array": {
                            "type": "string",
                            "description": "List of errors encountered when producing the report"
                        }
                    },
                    "trace": {
                        "array": {
                            "type": "string",
                            "description": "List of tracing information about the analyzer execution"
                        }
                    },
                    "warnings": {
                        "array": {
                            "type": "string",
                            "description": "List of warnings encountered when producing the report"
                        }
                    },
                    "coverages": {
                        "type": "array",
                        "description": "The coverages in percentage achieved in each contract",
                        "items": {
                            "type": "object",
                            "properties": {
                                "percentage": {
                                    "type": "number",
                                    "description": "The percentage value of bytecode statements covered during the audit",
                                    "minimum": 0,
                                    "maximum": 100
                                },
                                "file": {
                                    "type": "string",
                                    "description": "Audited contract file name",
                                    "maxLength": 1000
                                },
                                "contract": {
                                    "type": "string",
                                    "description": "Audited contract name",
                                    "maxLength": 1000
                                }
                            }
                        }
                    },
                    "potential_vulnerabilities": {
                        "type": "array",
                        "description": "List of potential vulnerabilities found",
                        "items": {
                            "title": "Vulnerability",
                            "description": "Descriptive data about each reported vulnerability",
                            "required": [
                                "type",
                                "file",
                                "instances"
                            ],
                            "properties": {
                                "type": {
                                    "type": "string",
                                    "description": "The type of the vulnerability reported by the analyzer",
                                    "maxLength": 1000
                                },                                
                                "file": {
                                    "type": "string",
                                    "description": "Audited contract file name",
                                    "maxLength": 1000
                                },
                                "contract": {
                                    "type": "string",
                                    "description": "Audited contract name",
                                    "maxLength": 1000
                                },
                                "instances": {
                                    "type": "array",
                                    "description": "Array of dictionaries describing each potential vulnerability",
                                    "items": {
                                        "required": [
                                            "ref_id",
                                            "start_line"
                                        ],
                                        "properties": {
                                            "ref_id": {
                                                "type": "integer",
                                                "description": "Reference identifier associated with this instance",
                                                "minimum": 0
                                            },
                                            "start_line": {
                                                "type": "integer",
                                                "description": "The initial line where the vulnerability was found",
                                                "minimum": 0
                                            },
                                            "end_line": {
                                                "type": "integer",
                                                "description": "The end line where the vulnerability was found",
                                                "minimum": 0
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
    }
}

=== DUMIE505/qsp-protocol-node/tests/resources/reports/DockerhubFailAllAnalyzers.json
{
  "timestamp": 1543602182,
  "contract_uri": "file:///app/tests/helpers/../resources/DAOBug.sol",
  "contract_hash": "b7f55bc69671c5f4fb295fd5acf1375eb7f1363093176f4bec190c39f95c235b",
  "requestor": "0x82A978B3f5962A5b0957d9ee9eEf472EE55B42F1",
  "auditor": "0x82A978B3f5962A5b0957d9ee9eEf472EE55B42F1",
  "request_id": 1,
  "version": "1.0.0",
  "audit_state": 5,
  "status": "error",
  "analyzers_reports": [
    {
      "status": "success",
      "warnings": [
        "root:You are using evm version 1.8.2. The supported version is 1.7.3",
        "root:You are using solc version 0.4.25, The latest supported version is 0.4.19"
      ],
      "coverages": [
        {
          "percentage": 98.4,
          "file": "DAOBug.sol",
          "contract": "SendBalance"
        }
      ],
      "potential_vulnerabilities": [
        {
          "type": "reentrancy",
          "file": "DAOBug.sol",
          "contract": "SendBalance",
          "instances": [
            {
              "ref_id": 0,
              "start_line": 25,
              "end_line": 25
            }
          ]
        }
      ],
      "analyzer": {
        "name": "oyente",
        "version": "f6b1697fd6607e4bb5c3104fb58d16e50e843254e983cd3735df510bb40b0ff8",
        "vulnerabilities_checked": {
          "integer_underflow": {
            "type": "integer_underflow"
          },
          "integer_overflow": {
            "type": "integer_overflow"
          },
          "callstack": {
            "type": "callstack"
          },
          "money_concurrency": {
            "type": "transaction_order_dependency"
          },
          "time_dependency": {
            "type": "time_dependency"
          },
          "reentrancy": {
            "type": "reentrancy"
          },
          "parity_multisig_bug_2": {
            "type": "parity_multisig_bug"
          },
          "assertion_failure": {
            "type": "exception_state"
          }
        },
        "command": "docker run --rm -v /tmp/.oyente/137:/shared/ -i qspprotocol/oyente-0.4.25@sha256:f6b1697fd6607e4bb5c3104fb58d16e50e843254e983cd3735df510bb40b0ff8 -ce -j -s /shared/DAOBug.sol"
      },
      "start_time": 1543602167,
      "end_time": 1543602182
    },
    {
      "status": "success",
      "potential_vulnerabilities": [
        {
          "type": "unprotected_ether_withdrawal",
          "file": "DAOBug.sol",
          "description": "In the function `withdrawBalance()` a non-zero amount of Ether is sent to msg.sender.\nIt seems that this function can be called without restrictions.",
          "instances": [
            {
              "ref_id": 0,
              "start_line": 25
            }
          ]
        },
        {
          "type": "call_to_external_contract",
          "file": "DAOBug.sol",
          "description": "This contract executes a message call to the address of the transaction sender. Generally, it is not recommended to call user-supplied addresses using Solidity's call() construct. Note that attackers might leverage reentrancy attacks to exploit race conditions or manipulate this contract's state.",
          "instances": [
            {
              "ref_id": 1,
              "start_line": 25
            }
          ]
        },
        {
          "type": "reentrancy",
          "file": "DAOBug.sol",
          "description": "The contract account state is changed after an external call. Consider that the called contract could re-enter the function before this state change takes place. This can lead to business logic vulnerabilities.",
          "instances": [
            {
              "ref_id": 2,
              "start_line": 29
            }
          ]
        }
      ],
      "analyzer": {
        "name": "mythril",
        "version": "9a5c1ad864df66e8cfb6ac1c283bab6f8fb25ebef0bf98405daaa04616e44316",
        "vulnerabilities_checked": {
          "Call data forwarded with delegatecall()": {
            "type": "delegate_call_to_untrusted_contract"
          },
          "Dependence on predictable environment variable": {
            "type": "dependence_on_environment_variable"
          },
          "Call to a user-supplied address": {
            "type": "delegate_call_to_untrusted_contract"
          },
          "Use of tx.origin": {
            "type": "tx_origin_usage"
          },
          "Ether send": {
            "type": "unprotected_ether_withdrawal"
          },
          "Exception state": {
            "type": "exception_state"
          },
          "Message call to external contract": {
            "type": "call_to_external_contract"
          },
          "State change after external call": {
            "type": "reentrancy"
          },
          "Integer Overflow": {
            "type": "integer_overflow"
          },
          "Integer Underflow": {
            "type": "integer_underflow"
          },
          "Multiple Calls": {
            "type": "multiple_calls"
          },
          "Unchecked SUICIDE": {
            "type": "unprotected_self_destruct"
          },
          "Transaction order dependence": {
            "type": "transaction_order_dependency"
          },
          "Unchecked CALL return value": {
            "type": "unchecked_call_return_value"
          },
          "Unknown": {
            "type": "other"
          }
        },
        "command": "docker run --rm -v /tmp/.mythril/149:/shared/ -i qspprotocol/mythril-0.4.25@sha256:9a5c1ad864df66e8cfb6ac1c283bab6f8fb25ebef0bf98405daaa04616e44316  -o json -x /shared/DAOBug.sol"
      },
      "start_time": 1543602167,
      "end_time": 1543602182
    },
    {
      "status": "error",
      "errors": [
        "Error response from daemon: pull access denied for qspprotocol/does-not-exist-0.4.25, repository does not exist or may require 'docker login'\n"
      ],
      "trace": [
        ">> Wrapper setup finished\n",
        ">> About to execute once script\n"
      ],
      "analyzer": {
        "name": "dockerhub_fail",
        "version": "9a5c1ad864df66e8cfb6ac1c283bab6f8fb25ebef0bf98405daaa04616e44316",
        "vulnerabilities_checked": {
          "Call data forwarded with delegatecall()": {
            "type": "delegate_call_to_untrusted_contract"
          },
          "Dependence on predictable environment variable": {
            "type": "dependence_on_environment_variable"
          },
          "Call to a user-supplied address": {
            "type": "delegate_call_to_untrusted_contract"
          },
          "Use of tx.origin": {
            "type": "tx_origin_usage"
          },
          "Ether send": {
            "type": "unprotected_ether_withdrawal"
          },
          "Exception state": {
            "type": "exception_state"
          },
          "Message call to external contract": {
            "type": "call_to_external_contract"
          },
          "State change after external call": {
            "type": "reentrancy"
          },
          "Integer Overflow": {
            "type": "integer_overflow"
          },
          "Integer Underflow": {
            "type": "integer_underflow"
          },
          "Multiple Calls": {
            "type": "multiple_calls"
          },
          "Unchecked SUICIDE": {
            "type": "unprotected_self_destruct"
          },
          "Transaction order dependence": {
            "type": "transaction_order_dependency"
          },
          "Unchecked CALL return value": {
            "type": "unchecked_call_return_value"
          },
          "Unknown": {
            "type": "other"
          }
        },
        "command": "docker run --rm -v /tmp/161:/shared/ -i qspprotocol/does-not-exist-0.4.25@sha256:9a5c1ad864df66e8cfb6ac1c283bab6f8fb25ebef0bf98405daaa04616e44316  -o json -x /shared/DAOBug.sol"
      },
      "start_time": 1543602167,
      "end_time": 1543602182
    }
  ],
  "compilation_warnings": [
    "DAOBug.sol:26:7: Warning: \"throw\" is deprecated in favour of \"revert()\", \"require()\" and \"assert()\".\n      throw;\n      ^---^\n",
    "DAOBug.sol:16:3: Warning: No visibility specified. Defaulting to \"public\". \n  function getBalance(address u) constant returns (uint) {\n  ^ (Relevant source part starts here and spans across multiple lines).\n",
    "DAOBug.sol:20:3: Warning: No visibility specified. Defaulting to \"public\". \n  function addToBalance() {\n  ^ (Relevant source part starts here and spans across multiple lines).\n",
    "DAOBug.sol:21:33: Warning: \"msg.value\" used in non-payable function. Do you want to add the \"payable\" modifier to this function?\n    userBalances[msg.sender] += msg.value;\n                                ^-------^\n",
    "DAOBug.sol:24:3: Warning: No visibility specified. Defaulting to \"public\". \n  function withdrawBalance() {\n  ^ (Relevant source part starts here and spans across multiple lines).\n"
  ]
}

=== DUMIE505/qsp-protocol-node/tests/resources/reports/DockerhubFail.json
{
  "timestamp": 1543618114,
  "contract_uri": "file:///app/tests/helpers/../resources/DAOBug.sol",
  "contract_hash": "b7f55bc69671c5f4fb295fd5acf1375eb7f1363093176f4bec190c39f95c235b",
  "requestor": "0x82A978B3f5962A5b0957d9ee9eEf472EE55B42F1",
  "auditor": "0x82A978B3f5962A5b0957d9ee9eEf472EE55B42F1",
  "request_id": 1,
  "version": "2.0.0",
  "audit_state": 5,
  "status": "error",
  "analyzers_reports": [
    {
      "status": "error",
      "errors": [
        "Error response from daemon: pull access denied for qspprotocol/does-not-exist-0.4.25, repository does not exist or may require 'docker login'\n"
      ],
      "trace": [
        ">> Wrapper setup finished\n",
        ">> About to execute once script\n"
      ],
      "analyzer": {
        "name": "dockerhub_fail",
        "version": "c6ad3380cc251ed8c6f59a3e21aafbfb5ceb41a487dbb38e5dfb6beddd123913",
        "vulnerabilities_checked": {
          "Call data forwarded with delegatecall()": {
            "type": "delegate_call_to_untrusted_contract"
          },
          "Dependence on predictable environment variable": {
            "type": "dependence_on_environment_variable"
          },
          "Call to a user-supplied address": {
            "type": "delegate_call_to_untrusted_contract"
          },
          "Use of tx.origin": {
            "type": "tx_origin_usage"
          },
          "Ether send": {
            "type": "unprotected_ether_withdrawal"
          },
          "Exception state": {
            "type": "exception_state"
          },
          "Message call to external contract": {
            "type": "call_to_external_contract"
          },
          "State change after external call": {
            "type": "reentrancy"
          },
          "Integer Overflow": {
            "type": "integer_overflow"
          },
          "Integer Underflow": {
            "type": "integer_underflow"
          },
          "Multiple Calls": {
            "type": "multiple_calls"
          },
          "Unchecked SUICIDE": {
            "type": "unprotected_self_destruct"
          },
          "Transaction order dependence": {
            "type": "transaction_order_dependency"
          },
          "Unchecked CALL return value": {
            "type": "unchecked_call_return_value"
          },
          "Unknown": {
            "type": "other"
          }
        },
        "command": "docker run --rm -v /tmp/1543618103.00930830.8891051666701546/725:/shared/ -i qspprotocol/does-not-exist-0.4.25@sha256:c6ad3380cc251ed8c6f59a3e21aafbfb5ceb41a487dbb38e5dfb6beddd123913  -o json -x /shared/DAOBug.sol"
      },
      "start_time": 1543618113,
      "end_time": 1543618114
    }
  ],
  "compilation_warnings": [
    "DAOBug.sol:26:7: Warning: \"throw\" is deprecated in favour of \"revert()\", \"require()\" and \"assert()\".\n      throw;\n      ^---^\n",
    "DAOBug.sol:16:3: Warning: No visibility specified. Defaulting to \"public\". \n  function getBalance(address u) constant returns (uint) {\n  ^ (Relevant source part starts here and spans across multiple lines).\n",
    "DAOBug.sol:20:3: Warning: No visibility specified. Defaulting to \"public\". \n  function addToBalance() {\n  ^ (Relevant source part starts here and spans across multiple lines).\n",
    "DAOBug.sol:21:33: Warning: \"msg.value\" used in non-payable function. Do you want to add the \"payable\" modifier to this function?\n    userBalances[msg.sender] += msg.value;\n                                ^-------^\n",
    "DAOBug.sol:24:3: Warning: No visibility specified. Defaulting to \"public\". \n  function withdrawBalance() {\n  ^ (Relevant source part starts here and spans across multiple lines).\n"
  ]
}
