=== DUMIE505/qsp-protocol-node/plugins/analyzers/schema/analyzer_integration.json
{
    "$schema": "http://json-schema.org/schema#",
    "id": "http://quantstamp.com/schemas/analyzer.json",
    "version": "0.0.1",
    "type": "object",
    "title": "Audit report",
    "description": "API schema defining the expected output format of an audit report",
    "additionalProperties": false,
    "required": [
        "status"
    ],
    "properties": {
        "timestamp": {
            "type": "integer",
            "description": "The UTC time in which in this report was produced"
        },
        "audit_state": {
            "type": "integer",
            "description": "The AuditState of the report, as defined in QuantstampAuditData",
            "minimum": 0,
            "maximum": 6
        },
        "version": {
            "type": "string",
            "description": "The version of the audit node"
        },
        "contract_uri": {
            "type": "string",
            "description": "The UTC time in which in this report was produced"
        },
        "contract_hash": {
            "type": "string",
            "pattern": "^[A-Fa-f0-9]{64}$",
            "description": "Hash digest (sha256) of the target contract" 
        },
        "compilation_errors": {
            "type": "array",
            "items": {
                "type": "string"
            },
            "description": "The list of compilation errors preventing the code from compiling"
        },
        "compilation_warnings": {
            "type": "array",
            "items": {
                "type": "string"
            },
            "description": "The list of compilation warnings that do not prevent the code from compiling"
        },
        "requestor": {
            "type": "string",
            "pattern": "^(0x)?[A-Fa-f0-9]{40}$",
            "description": "The account address of the party requesting the audit"
        },
        "auditor": {
            "type": "string",
            "pattern": "^(0x)?[A-Fa-f0-9]{40}$",
            "description": "The account address of the party producing the audit"
        },
        "request_id": {
            "type": "integer"
        },
        "status": {
            "type": "string",
            "enum": [
                "success",
                "error"
            ],
            "description": "Status result of whether the audit was successfully produced or not"
        },
        "analyzers_reports": {
            "type": "array",
            "items": {
                "type": "object",
                "required": [
                    "analyzer",
                    "status"
                ],
                "properties": {
                    "start_time": {
                        "type": "integer",
                        "description": "The starting time (epoch) that the analyzer started execution",
                        "minimum": 1                    
                    },
                    "end_time": {
                        "type": "integer",
                        "description": "The end time (epoch) that the analyzer ended execution",
                        "minimum": 1                    
                    },
                    "analyzer": {
                        "type":  "object",
                        "description": "Meta data concerning the underlying analyzer",
                        "required": ["name"],
                        "properties": {
                            "name": {
                                "description": "Analyzer's name",
                                "type": "string",
                                "maxLength": 50
                            },
                            "version": {
                                "description": "Analyzer's version",
                                "type": "string",
                                "maxLength": 64
                            },
                            "vulnerabilities_checked": {
                                "type": "object",
                                "patternProperties": {
                                    "^.*$": { 
                                        "type": "object",
                                        "properties": {
                                            "type": {
                                                "type": "string"
                                            }
                                        },
                                        "required": ["type"]
                                    }
                                }                     
                            },
                            "command": {
                                "type": "string",
                                "description": "Command used when executing the analyzer for the given report"
                            }
                        }
                    },
                    "status": {
                        "enum": ["success", "error"],
                        "description": "Status result of whether the analyzer succeeded or not"
                    },
                    "errors": {
                        "array": {
                            "type": "string",
                            "description": "List of errors encountered when producing the report"
                        }
                    },
                    "trace": {
                        "array": {
                            "type": "string",
                            "description": "List of tracing information about the analyzer execution"
                        }
                    },
                    "warnings": {
                        "array": {
                            "type": "string",
                            "description": "List of warnings encountered when producing the report"
                        }
                    },
                    "coverages": {
                        "type": "array",
                        "description": "The coverages in percentage achieved in each contract",
                        "items": {
                            "type": "object",
                            "properties": {
                                "percentage": {
                                    "type": "number",
                                    "description": "The percentage value of bytecode statements covered during the audit",
                                    "minimum": 0,
                                    "maximum": 100
                                },
                                "file": {
                                    "type": "string",
                                    "description": "Audited contract file name",
                                    "maxLength": 1000
                                },
                                "contract": {
                                    "type": "string",
                                    "description": "Audited contract name",
                                    "maxLength": 1000
                                }
                            }
                        }
                    },
                    "potential_vulnerabilities": {
                        "type": "array",
                        "description": "List of potential vulnerabilities found",
                        "items": {
                            "title": "Vulnerability",
                            "description": "Descriptive data about each reported vulnerability",
                            "required": [
                                "type",
                                "file",
                                "instances"
                            ],
                            "properties": {
                                "type": {
                                    "type": "string",
                                    "description": "The type of the vulnerability reported by the analyzer",
                                    "maxLength": 1000
                                },                                
                                "file": {
                                    "type": "string",
                                    "description": "Audited contract file name",
                                    "maxLength": 1000
                                },
                                "contract": {
                                    "type": "string",
                                    "description": "Audited contract name",
                                    "maxLength": 1000
                                },
                                "instances": {
                                    "type": "array",
                                    "description": "Array of dictionaries describing each potential vulnerability",
                                    "items": {
                                        "required": [
                                            "ref_id",
                                            "start_line"
                                        ],
                                        "properties": {
                                            "ref_id": {
                                                "type": "integer",
                                                "description": "Reference identifier associated with this instance",
                                                "minimum": 0
                                            },
                                            "start_line": {
                                                "type": "integer",
                                                "description": "The initial line where the vulnerability was found",
                                                "minimum": 0
                                            },
                                            "end_line": {
                                                "type": "integer",
                                                "description": "The end line where the vulnerability was found",
                                                "minimum": 0
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
    }
}

=== DUMIE505/qsp-protocol-node/tests/resources/reports/Empty.json
{
  "timestamp": 1542045974,
  "contract_uri": "file:///app/tests/helpers/../resources/Empty.sol",
  "contract_hash": "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855",
  "requestor": "0x7E5F4552091A69125d5DfCb7b8C2659029395Bdf",
  "auditor": "0x7E5F4552091A69125d5DfCb7b8C2659029395Bdf",
  "request_id": 1,
  "version": "2.0.0",
  "audit_state": 5,
  "status": "error",
  "analyzers_reports": [
    {
      "status": "error",
      "errors": [
        "Traceback (most recent call last):\n",
        "  File \"/usr/local/bin/myth\", line 4, in <module>\n",
        "    __import__('pkg_resources').run_script('mythril==0.18.6', 'myth')\n",
        "  File \"/usr/lib/python3/dist-packages/pkg_resources/__init__.py\", line 658, in run_script\n",
        "    self.require(requires)[0].run_script(script_name, ns)\n",
        "  File \"/usr/lib/python3/dist-packages/pkg_resources/__init__.py\", line 1438, in run_script\n",
        "    exec(code, namespace, namespace)\n",
        "  File \"/usr/local/lib/python3.6/dist-packages/mythril-0.18.6-py3.6.egg/EGG-INFO/scripts/myth\", line 9, in <module>\n",
        "    mythril.interfaces.cli.main()\n",
        "  File \"/usr/local/lib/python3.6/dist-packages/mythril-0.18.6-py3.6.egg/mythril/interfaces/cli.py\", line 159, in main\n",
        "    address, _ = mythril.load_from_solidity(args.solidity_file)  # list of files\n",
        "  File \"/usr/local/lib/python3.6/dist-packages/mythril-0.18.6-py3.6.egg/mythril/mythril.py\", line 305, in load_from_solidity\n",
        "    contract = SolidityContract(file, contract_name, solc_args=self.solc_args)\n",
        "  File \"/usr/local/lib/python3.6/dist-packages/mythril-0.18.6-py3.6.egg/mythril/ether/soliditycontract.py\", line 62, in __init__\n",
        "    for key, contract in data['contracts'].items():\n",
        "KeyError: 'contracts'\n"
      ],
      "trace": [
        ">> Wrapper setup finished\n",
        ">> About to execute once script\n",
        ">> Done\n",
        ">> About to execute pre_run script\n",
        "sha256:e7ef40718273b6d400d45669500dd63a7017215aa8c5748fb3ff91faac73ad95: Pulling from qspprotocol/mythril-usolc-0.5.3\n",
        "Digest: sha256:e7ef40718273b6d400d45669500dd63a7017215aa8c5748fb3ff91faac73ad95\n",
        "Status: Image is up to date for qspprotocol/mythril-usolc-0.5.3@sha256:e7ef40718273b6d400d45669500dd63a7017215aa8c5748fb3ff91faac73ad95\n",
        ">> Done\n",
        ">> Copying contract(s) to docker's mounted volume\n",
        ">> Done\n",
        ">> About to invoke mythril\n",
        ">> Done\n"
      ],
      "analyzer": {
        "name": "mythril",
        "version": "e7ef40718273b6d400d45669500dd63a7017215aa8c5748fb3ff91faac73ad95",
        "vulnerabilities_checked": {
          "Call data forwarded with delegatecall()": {
            "type": "delegate_call_to_untrusted_contract"
          },
          "Dependence on predictable environment variable": {
            "type": "dependence_on_environment_variable"
          },
          "Call to a user-supplied address": {
            "type": "delegate_call_to_untrusted_contract"
          },
          "Use of tx.origin": {
            "type": "tx_origin_usage"
          },
          "Ether send": {
            "type": "unprotected_ether_withdrawal"
          },
          "Exception state": {
            "type": "exception_state"
          },
          "Message call to external contract": {
            "type": "call_to_external_contract"
          },
          "State change after external call": {
            "type": "reentrancy"
          },
          "Integer Overflow": {
            "type": "integer_overflow"
          },
          "Integer Underflow": {
            "type": "integer_underflow"
          },
          "Multiple Calls": {
            "type": "multiple_calls"
          },
          "Unchecked SUICIDE": {
            "type": "unprotected_self_destruct"
          },
          "Transaction order dependence": {
            "type": "transaction_order_dependency"
          },
          "Unchecked CALL return value": {
            "type": "unchecked_call_return_value"
          },
          "Unknown": {
            "type": "other"
          }
        },
        "command": "docker run --rm -v /tmp/.mythril/1538:/shared/ -i qspprotocol/mythril-usolc-0.5.3@sha256:e7ef40718273b6d400d45669500dd63a7017215aa8c5748fb3ff91faac73ad95  -o json -x /shared/Empty.sol"
      },
      "start_time": 1542045970,
      "end_time": 1542045973
    },
    {
      "status": "error",
      "errors": [
        "Exception in thread \"main\" java.lang.NullPointerException\n",
        "\tat ch.securify.CompilationHelpers.compileContracts(CompilationHelpers.java:102)\n",
        "\tat ch.securify.Main.processSolidityFile(Main.java:91)\n",
        "\tat ch.securify.Main.main(Main.java:186)\n"
      ],
      "trace": [
        ">> Wrapper setup finished\n",
        ">> About to execute once script\n",
        ">> Done\n",
        ">> About to execute pre_run script\n",
        "sha256:a1fb59473db3e15c7b6deb756d2f1c09d57074db75105ca6eff41a3f28c6eb4e: Pulling from qspprotocol/securify-usolc-0.5.3\n",
        "Digest: sha256:a1fb59473db3e15c7b6deb756d2f1c09d57074db75105ca6eff41a3f28c6eb4e\n",
        "Status: Image is up to date for qspprotocol/securify-usolc-0.5.3@sha256:a1fb59473db3e15c7b6deb756d2f1c09d57074db75105ca6eff41a3f28c6eb4e\n",
        ">> Done\n",
        ">> Copying contract(s) to docker's mounted volume\n",
        ">> Done\n",
        ">> About to invoke securify\n"
      ],
      "analyzer": {
        "name": "securify",
        "version": "a1fb59473db3e15c7b6deb756d2f1c09d57074db75105ca6eff41a3f28c6eb4e",
        "vulnerabilities_checked": {
          "MissingInputValidation": {
            "type": "missing_input_validation"
          },
          "LockedEther": {
            "type": "locked_ether"
          },
          "UnrestrictedWrite": {
            "type": "unprotected_state_manipulation"
          },
          "UnrestrictedEtherFlow": {
            "type": "unprotected_ether_withdrawal"
          },
          "UnhandledException": {
            "type": "exception_state"
          },
          "DAO": {
            "type": "reentrancy"
          },
          "DAOConstantGas": {
            "type": "reentrancy"
          },
          "TODReceiver": {
            "type": "transaction_order_dependency"
          },
          "TODTransfer": {
            "type": "transaction_order_dependency"
          },
          "TODAmount": {
            "type": "transaction_order_dependency"
          },
          "MissingInputValidationTP": {
            "type": "missing_input_validation_true_positive"
          },
          "LockedEtherTP": {
            "type": "locked_ether_true_positive"
          },
          "UnrestrictedWriteTP": {
            "type": "unprotected_state_manipulation_true_positive"
          },
          "UnrestrictedEtherFlowTP": {
            "type": "unprotected_ether_withdrawal_true_positive"
          },
          "UnhandledExceptionTP": {
            "type": "exception_state_true_positive"
          },
          "DAOTP": {
            "type": "reentrancy_true_positive"
          },
          "DAOConstantGasTP": {
            "type": "reentrancy_true_positive"
          },
          "TODReceiverTP": {
            "type": "transaction_order_dependency_true_positive"
          },
          "TODTransferTP": {
            "type": "transaction_order_dependency_true_positive"
          },
          "TODAmountTP": {
            "type": "transaction_order_dependency_true_positive"
          },
          "SecurifyBug": {
            "type": "securify_bug"
          },
          "Unknown": {
            "type": "other"
          }
        },
        "command": "docker run --rm -v /tmp/.securify/1550:/shared/ -i qspprotocol/securify-usolc-0.5.3@sha256:a1fb59473db3e15c7b6deb756d2f1c09d57074db75105ca6eff41a3f28c6eb4e  -fs /shared/Empty.sol"
      },
      "start_time": 1542045970,
      "end_time": 1542045974
    }
  ],
  "compilation_warnings": [
    "Empty.sol:1:1: Warning: Source file does not specify required compiler version!Consider adding \"pragma solidity ^0.4.25;\"\n\n^\n"
  ]
}

=== DUMIE505/qsp-protocol-node/tests/resources/reports/BasicToken.json
{
  "timestamp": 1535474053,
  "contract_uri": "file:///app/tests/helpers/../resources/BasicToken.sol",
  "contract_hash": "95d939e9830d5c6c2b393851d8e789d041026cd0ddd75764902b8731945f9a96",
  "requestor": "0x7E5F4552091A69125d5DfCb7b8C2659029395Bdf",
  "auditor": "0x7E5F4552091A69125d5DfCb7b8C2659029395Bdf",
  "request_id": 1,
  "version": "2.0.1",
  "audit_state": 5,
  "status": "error",
  "compilation_errors": [
    "BasicToken.sol:11:1: ParserError: Source \"ERC20Basic.sol\" not found: File outside of allowed directories.\nimport \"./ERC20Basic.sol\";\n^------------------------^\n\nBasicToken.sol:12:1: ParserError: Source \"math/SafeMath.sol\" not found: File outside of allowed directories.\nimport \"../../math/SafeMath.sol\";\n^-------------------------------^\n\n        > command: `solc --standard-json`\n        > return code: `0`\n        > stderr:\n        {\"contracts\":{},\"errors\":[{\"component\":\"general\",\"formattedMessage\":\"BasicToken.sol:11:1: ParserError: Source \\\"ERC20Basic.sol\\\" not found: File outside of allowed directories.\\nimport \\\"./ERC20Basic.sol\\\";\\n^------------------------^\\n\",\"message\":\"Source \\\"ERC20Basic.sol\\\" not found: File outside of allowed directories.\",\"severity\":\"error\",\"sourceLocation\":{\"end\":660,\"file\":\"BasicToken.sol\",\"start\":634},\"type\":\"ParserError\"},{\"component\":\"general\",\"formattedMessage\":\"BasicToken.sol:12:1: ParserError: Source \\\"math/SafeMath.sol\\\" not found: File outside of allowed directories.\\nimport \\\"../../math/SafeMath.sol\\\";\\n^-------------------------------^\\n\",\"message\":\"Source \\\"math/SafeMath.sol\\\" not found: File outside of allowed directories.\",\"severity\":\"error\",\"sourceLocation\":{\"end\":694,\"file\":\"BasicToken.sol\",\"start\":661},\"type\":\"ParserError\"}],\"sources\":{}}\n\n        > stdout:"
  ]
}

=== DUMIE505/qsp-protocol-node/tests/resources/reports/DappBinWallet.json
{
  "timestamp": 1554850200,
  "contract_uri": "file:///app/tests/helpers/../resources/DappBinWallet.sol",
  "contract_hash": "71d923c4ff8679e431796020145e9eafff445ccefc47041f588a540233f327e0",
  "requestor": "0x7E5F4552091A69125d5DfCb7b8C2659029395Bdf",
  "auditor": "0x7E5F4552091A69125d5DfCb7b8C2659029395Bdf",
  "request_id": 1,
  "version": "2.0.1",
  "audit_state": 5,
  "status": "error",
  "compilation_errors": [
    "DappBinWallet.sol:12:1: ParserError: Expected pragma, import directive or contract/interface/library definition.\n<!DOCTYPE html>\n^\n\n        > command: `solc --standard-json`\n        > return code: `0`\n        > stderr:\n        {\"errors\":[{\"component\":\"general\",\"formattedMessage\":\"DappBinWallet.sol:12:1: ParserError: Expected pragma, import directive or contract/interface/library definition.\\n<!DOCTYPE html>\\n^\\n\",\"message\":\"Expected pragma, import directive or contract/interface/library definition.\",\"severity\":\"error\",\"sourceLocation\":{\"end\":612,\"file\":\"DappBinWallet.sol\",\"start\":611},\"type\":\"ParserError\"}],\"sources\":{}}\n\n        > stdout:"
  ]
}

=== DUMIE505/qsp-protocol-node/tests/resources/reports/DAOBugDecompressed.json
{
  "analyzers_reports": [
    {
      "analyzer": {
        "name": "Unknown Analyzer"
      },
      "potential_vulnerabilities": [
        {
          "file": "Unknown File",
          "instances": [
            {
              "end_line": 23,
              "ref_id": 0,
              "start_line": 23
            }
          ],
          "type": "unprotected_ether_withdrawal"
        },
        {
          "file": "Unknown File",
          "instances": [
            {
              "end_line": 23,
              "ref_id": 0,
              "start_line": 23
            }
          ],
          "type": "call_to_external_contract"
        },
        {
          "file": "Unknown File",
          "instances": [
            {
              "end_line": 27,
              "ref_id": 0,
              "start_line": 27
            }
          ],
          "type": "reentrancy"
        },
        {
          "file": "Unknown File",
          "instances": [
            {
              "end_line": 23,
              "ref_id": 0,
              "start_line": 23
            }
          ],
          "type": "transaction_order_dependency"
        },
        {
          "file": "Unknown File",
          "instances": [
            {
              "end_line": 23,
              "ref_id": 0,
              "start_line": 23
            }
          ],
          "type": "unchecked_call_return_value"
        },
        {
          "file": "Unknown File",
          "instances": [
            {
              "end_line": 23,
              "ref_id": 0,
              "start_line": 23
            }
          ],
          "type": "reentrancy_true_positive"
        },
        {
          "file": "Unknown File",
          "instances": [
            {
              "end_line": 14,
              "ref_id": 0,
              "start_line": 14
            }
          ],
          "type": "missing_input_validation_true_positive"
        },
        {
          "file": "Unknown File",
          "instances": [
            {
              "end_line": 22,
              "ref_id": 0,
              "start_line": 22
            },
            {
              "end_line": 18,
              "ref_id": 1,
              "start_line": 18
            }
          ],
          "type": "missing_input_validation"
        }
      ],
      "status": "success"
    }
  ],
  "audit_state": 4,
  "contract_hash": "DC996A1C50B01EA3EC370A45CE43394F22BC0DFDA4DD43990CEDCDC505E593BF",
  "status": "success",
  "version": "2.0.1"
}
